In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [2]:
vectorizer = CountVectorizer()

In [3]:
corpus = [
  'слово1 слово2 слово3',
  'слово2 слово3',
  'слово1 слово2 слово1',
  'слово4'
]

In [4]:
X = vectorizer.fit_transform(corpus)
# count

In [5]:
X

<4x4 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [7]:
X.toarray()
# show the matrix

array([[1, 1, 1, 0],
       [0, 1, 1, 0],
       [2, 1, 0, 0],
       [0, 0, 0, 1]])

In [13]:
vectorizer.get_feature_names()
# get the vocabulary

['слово1', 'слово2', 'слово3', 'слово4']

In [16]:
vectorizer.vocabulary_.get('слово3')
# get index of word

2

In [20]:
m = vectorizer.transform(['слово1 слово4 слово4'])
# count vector for a new document

In [21]:
m.toarray()

array([[1, 0, 0, 2]])

In [22]:
matrix_freq = np.asarray(X.sum(axis=0)).ravel()
# converts a sequence to a NumPy array and count words
# ravel() returns an array compressed to one axis

In [23]:
matrix_freq

array([3, 3, 2, 1])

In [25]:
final_matrix = np.array([np.array(vectorizer.get_feature_names()), 
                         matrix_freq])

In [26]:
final_matrix

array([['слово1', 'слово2', 'слово3', 'слово4'],
       ['3', '3', '2', '1']], dtype='<U21')