In [1]:
from sklearn.datasets import fetch_20newsgroups

In [2]:
categories = ['alt.atheism', 
              'soc.religion.christian', 
              'comp.graphics',
              'sci.med']

In [3]:
twenty_train = fetch_20newsgroups(subset='train', categories=categories,
                                 shuffle=True, random_state=42)
# parametr shuffle shuffles(mixes) the sequence

In [4]:
twenty_train.data[0]

'From: sd345@city.ac.uk (Michael Collier)\nSubject: Converting images to HP LaserJet III?\nNntp-Posting-Host: hampton\nOrganization: The City University\nLines: 14\n\nDoes anyone know of a good way (standard PC application/PD utility) to\nconvert tif/img/tga files into LaserJet III format.  We would also like to\ndo the same, converting to HPGL (HP plotter) files.\n\nPlease email any response.\n\nIs this the correct group?\n\nThanks in advance.  Michael.\n-- \nMichael Collier (Programmer)                 The Computer Unit,\nEmail: M.P.Collier@uk.ac.city                The City University,\nTel: 071 477-8000 x3769                      London,\nFax: 071 477-8565                            EC1V 0HB.\n'

In [5]:
len(twenty_train.data)

2257

In [6]:
len(twenty_train.filenames)

2257

In [7]:
print('\n'.join(twenty_train.data[0].split('\n')[:]))

From: sd345@city.ac.uk (Michael Collier)
Subject: Converting images to HP LaserJet III?
Nntp-Posting-Host: hampton
Organization: The City University
Lines: 14

Does anyone know of a good way (standard PC application/PD utility) to
convert tif/img/tga files into LaserJet III format.  We would also like to
do the same, converting to HPGL (HP plotter) files.

Please email any response.

Is this the correct group?

Thanks in advance.  Michael.
-- 
Michael Collier (Programmer)                 The Computer Unit,
Email: M.P.Collier@uk.ac.city                The City University,
Tel: 071 477-8000 x3769                      London,
Fax: 071 477-8565                            EC1V 0HB.



In [8]:
twenty_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [9]:
twenty_train.target

array([1, 1, 3, ..., 2, 2, 2])

In [10]:
for i in twenty_train.target:
    print(twenty_train.target_names[i])

comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med
soc.religion.christian
comp.graphics
alt.atheism
alt.atheism
comp.graphics
comp.graphics
sci.med
alt.atheism
soc.religion.christian
alt.atheism
soc.religion.christian
alt.atheism
soc.religion.christian
comp.graphics
comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med
soc.religion.christian
sci.med
soc.religion.christian
sci.med
soc.religion.christian
alt.atheism
alt.atheism
alt.atheism
comp.graphics
soc.religion.christian
alt.atheism
comp.graphics
comp.graphics
sci.med
alt.atheism
soc.religion.christian
soc.religion.christian
comp.graphics
sci.med
comp.graphics
sci.med
alt.atheism
alt.atheism
sci.med
comp.graphics
sci.med
soc.religion.christian
alt.atheism
comp.graphics
alt.atheism
soc.religion.christian
comp.graphics
sci.med
comp.graphics
comp.graphics
sci.med
alt.atheism
soc

alt.atheism
comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
comp.graphics
comp.graphics
sci.med
sci.med
alt.atheism
sci.med
comp.graphics
sci.med
soc.religion.christian
alt.atheism
sci.med
alt.atheism
alt.atheism
sci.med
comp.graphics
sci.med
alt.atheism
alt.atheism
sci.med
soc.religion.christian
sci.med
comp.graphics
comp.graphics
comp.graphics
sci.med
comp.graphics
alt.atheism
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
alt.atheism
comp.graphics
soc.religion.christian
comp.graphics
alt.atheism
soc.religion.christian
comp.graphics
comp.graphics
comp.graphics
comp.graphics
alt.atheism
comp.graphics
sci.med
alt.atheism
soc.religion.christian
sci.med
soc.religion.christian
sci.med
alt.atheism
comp.graphics
sci.med
soc.religion.christian
sci.med
sci.med
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
soc.religion.christian
soc.religion.christian
sci.med
soc.religion

alt.atheism
sci.med
sci.med
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
comp.graphics
soc.religion.christian
comp.graphics
alt.atheism
alt.atheism
soc.religion.christian
soc.religion.christian
alt.atheism
comp.graphics
alt.atheism
alt.atheism
sci.med
comp.graphics
alt.atheism
sci.med
sci.med
sci.med
comp.graphics
comp.graphics
sci.med
sci.med
sci.med
soc.religion.christian
soc.religion.christian
comp.graphics
soc.religion.christian
alt.atheism
sci.med
sci.med
sci.med
sci.med
sci.med
sci.med


In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
count_vect = CountVectorizer()

In [13]:
X_train_counts = count_vect.fit_transform(twenty_train.data)

In [14]:
X_train_counts.shape

(2257, 35788)

In [15]:
count_vect.vocabulary_.get(u'algorithm')

4690

In [16]:
from sklearn.feature_extraction.text import TfidfTransformer

In [17]:
tfidf_transformer = TfidfTransformer()

In [18]:
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)

In [19]:
from sklearn.naive_bayes import MultinomialNB

In [20]:
clf = MultinomialNB().fit(X_train_tfidf, twenty_train.target)

In [21]:
docs_new = ['God is love', 'OpenGL on the GPU is fast']

In [22]:
X_new_counts = count_vect.transform(docs_new)

In [23]:
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

In [24]:
predicted = clf.predict(X_new_tfidf)

In [25]:
for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, twenty_train.target_names[category]))

'God is love' => soc.religion.christian
'OpenGL on the GPU is fast' => comp.graphics


In [26]:
from sklearn.pipeline import Pipeline

In [27]:
text_clf = Pipeline([('vect', CountVectorizer()),
                    ('tfidf', TfidfTransformer()),
                    ('clf', MultinomialNB())])

In [28]:
text_clf

Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', MultinomialNB())])

In [29]:
text_clf = text_clf.fit(twenty_train.data, twenty_train.target)

In [30]:
import numpy as np

In [31]:
twenty_test = fetch_20newsgroups(subset='test', categories=categories,
                                shuffle=True, random_state=42)

In [32]:
docs_test = twenty_test.data

In [33]:
predicted = text_clf.predict(docs_test)

In [34]:
np.mean(predicted == twenty_test.target)

0.8348868175765646

In [35]:
predicted

array([2, 2, 3, ..., 2, 2, 1])

In [36]:
from sklearn.linear_model import SGDClassifier
text_clf = Pipeline([('vect', CountVectorizer()),
                    ('tfidf', TfidfTransformer()),
                    ('clf', SGDClassifier())])
text_clf = text_clf.fit(twenty_train.data, twenty_train.target)
predicted = text_clf.predict(docs_test)
np.mean(predicted == twenty_test.target)

0.9287616511318242

In [37]:
from sklearn import metrics

In [38]:
metrics.classification_report(twenty_test.target, predicted, 
                              target_names=twenty_test.target_names)

'                        precision    recall  f1-score   support\n\n           alt.atheism       0.95      0.85      0.90       319\n         comp.graphics       0.91      0.97      0.94       389\n               sci.med       0.96      0.92      0.94       396\nsoc.religion.christian       0.90      0.96      0.93       398\n\n              accuracy                           0.93      1502\n             macro avg       0.93      0.92      0.93      1502\n          weighted avg       0.93      0.93      0.93      1502\n'

In [39]:
metrics.confusion_matrix(twenty_test.target, predicted)

array([[270,   7,   8,  34],
       [  4, 377,   4,   4],
       [  4,  23, 365,   4],
       [  5,   7,   3, 383]])

In [40]:
from sklearn.model_selection import GridSearchCV

In [41]:
parameters = {'vect_ngram_range': [(1, 1), (1, 2)],
            'tfidf_use_idf': (True, False),
             'clf__alpha': (1e-2, 1e-3),}

In [42]:
gs_clf = GridSearchCV(text_clf, parameters, n_jobs=-1)

In [43]:
gs_clf = gs_clf.fit(twenty_train.data[:400], twenty_train.target[:400])

ValueError: Invalid parameter tfidf_use_idf for estimator Pipeline(steps=[('vect', CountVectorizer()), ('tfidf', TfidfTransformer()),
                ('clf', SGDClassifier())]). Check the list of available parameters with `estimator.get_params().keys()`.

In [ ]:
sorted(text_clf.get_params().keys())